# Generated by Django 4.0.2 on 2022-02-26 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_profile_first_name_profile_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
